desafio5/flan/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.index, name='index_flan'),
    path('create/', views.create, name='create_flan'),
]

desafio5/project_onlyflans/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('web/', include('web.urls')),
    path('flan/', include('flan.urls')),
]

desafio5/web/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.index, name='index_web'),
    path('about/', views.about, name='about_web'),
    path('welcome/', views.welcome, name='welcome_web'),
    # crear path contact
    path('contact/', views.contact, name='contact_web'),
    # crear lista contacto web
    path('list_contact/', views.list_contact, name='list_contact_web'),

]

desafio5/flan/models.py
from django.db import models

# Create your models Flan here.

# Crear clase flan y sus campos


class Flan(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    image_url = models.URLField()
    shortName = models.SlugField()
    is_private = models.BooleanField()


def __str__(self):
    return self.name


# crear contactFrom

class ContactForm(models.Model):
    customer_email = models.EmailField()
    customer_name = models.CharField(max_length=64)
    message = models.TextField()

    def __str__(self):
        return self.customer_email
    

desafio5/web/models.py
from django.db import models

# Create your models here.

desafio5/flan/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Flan

# Create your views here.


def index(request):
    flans = Flan.objects.all()

    context = {"flans": flans}
    return render(request, "flan/index.html", context)


def create(request):
    if request.method == "POST":
        name = request.POST.get("name")
        description = request.POST.get("description")
        image_url = request.POST.get("image_url")
        shortName = request.POST.get("shortName")
        is_private = request.POST.get("is_private")
        if is_private == "on":
            is_private = True
        else:
            is_private = False
        flan = Flan(
            name=name,
            description=description,
            image_url=image_url,
            shortName=shortName,
            is_private=is_private,
        )
        flan.save()
        return render(request, "flan/index.html")
    return render(request, "flan/create.html")

desafio5/project_onlyflans/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'index.html')

desafio5/web/views.py
from django.shortcuts import render
from django.http import HttpResponse
from flan.models import Flan, ContactForm


# Create your views here.

def index(request):
    # este comando me trae todo los objetos flanes
    # flans = Flan.objects.all()
    # Filtrar los objetos o elemento que quiero mostrar
    flans = Flan.objects.filter(is_private=False)
    context = {
        'flans': flans
    }
    return render(request, 'web/index.html', context)

def about(request):
    return render(request, 'web/about.html')

def welcome(request):
    flans = Flan.objects.filter(is_private=True)
    context = {
        'flans': flans
    }
    return render(request, 'web/welcome.html', context)

# contact

def contact(request):
    if request.method == 'POST':
        customer_email = request.POST.get('customer_email')
        customer_name = request.POST.get('customer_name')
        message = request.POST.get('message')
        contact = ContactForm(customer_email=customer_email,customer_name=customer_name,message=message)
        contact.save()
        return render(request, 'web/contact_success.html')
    
    return render(request, 'web/contact.html')

# listas cotacto

def list_contact(request):
    contacts = ContactForm.objects.all()
    context = {'contacts': contacts}
    return render(request, 'web/list_contact.html',context)

desafio5/templates/flan/create.html
{% extends '../layouts/base.html' %}

{% block title %}
OnlyFlan | Crear Flan
{% endblock %}

{% block content %}
<div class="text-center my-4">
    <h1>Página para crear Flan</h1>
    <a href="{% url 'index_flan' %}" class="btn btn-secondary my-2">Volver</a>
</div>
<div class="d-flex justify-content-center">
    <form class="container border border-warning p-4" method="post" style="max-width: 600px;">
        {% csrf_token %}
        <div class="mb-3 text-center">
            <label class="form-label" for="name">Nombre Flan</label>
            <input class="form-control" type="text" name="name" id="id_name" placeholder="Ingrese nombre">
        </div>
        <div class="mb-3 text-center">
            <label class="form-label" for="description">Descripción Flan</label>
            <input class="form-control" type="text" name="description" id="id_description"
                placeholder="Ingrese descripción">
        </div>
        
        <div class="mb-3 text-center">
            <label class="form-label" for="image_url">URL Imagen Flan</label>
            <input class="form-control" type="text" name="image_url" id="id_image_url"
                placeholder="Ingrese URL de imagen">
        </div>
        <div class="mb-3 text-center">
            <label class="form-label" for="shortName">Nombre Corto Flan</label>
            <input class="form-control" type="text" name="shortName" id="id_shortName"
                placeholder="Ingrese nombre corto">
        </div>
        
        <!-- crear un checkbox privado -->
    
        <div class="mb-3 form-check">
            <input class="form-check-input" type="checkbox" name="id_private" id="id_is_private">
            <label class="form-check-label" for="id_private">Flan Privado</label>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Registrar</button>
        </div>
    </form>
</div>
{% endblock %}

desafio5/templates/flan/index.html
{% extends '../layouts/base.html' %}

{% block title %}
    OnlyFlan|Flan
{% endblock %}

{% block content %}
<div class="text-center">
    <h1 class="text-center">Listado de Flans</h1>
    <a href="{% url 'create_flan' %}" class="btn btn-primary mb-3">Crear Flan</a>
</div>    

    <div class="container-fluid" style="max-height: 500px; overflow-y:auto;">
        <div class="row">
            {% for flan in flans  %}
                <div class="col-md-3">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ flan.image_url }}" class="card-img-top" alt="{{ flan.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ flan.short_name }}</h5>
                            <p class="card-text">{{ flan.description }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

desafio5/templates/index.html
{% extends './layouts/base.html' %}


{% block title %}
    OnlyFlans
{% endblock  %}
    
<!-- contenido -->


{% block content %}
    <h1>Pagina principal del proyecto</h1>
{% endblock  %}
    

desafio5/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    {% include './partials/header.html' %}
    {% include './partials/navbar.html' %}
    <main>
        {% block content %} {% endblock %}
    </main>
    {% include './partials/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

desafio5/templates/layouts/partials/footer.html
<footer class="text-center bg-primary fixed-bottom p-2">
    <p> &copy Todos los derechos reservados para OnlyFlans 2024</p>
</footer>

desafio5/templates/layouts/partials/header.html
<header class="container-fluid bg-danger">
    <h1 class="text-center">OnlyFlans</h1>
</header>

desafio5/templates/layouts/partials/navbar.html
<nav class="navbar navbar-expand-lg bg-warning">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index_web'%}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about_web'%}">Acerca</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'welcome_web'%}" >Bienvenidos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index_flan' %}">Listado de Flanes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact_web' %}" >Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'list_contact_web' %}" >Lista contacto</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

desafio5/templates/web/about.html
{% extends '../layouts/base.html' %}


{% block title %}
    OnlyFlans | Acerca
{% endblock  %}


{% block content %}
    <h1 class="text-center">Pagina Acerca | WEB</h1>
{% endblock  %}
    
    

desafio5/templates/web/contact.html
{% extends '../layouts/base.html' %}


{% block title %}
OnlyFlans | Contacto
{% endblock %}


{% block content %}
<div class="text-center my-4">
    <h1>Página Contacto</h1>
    <a href="{% url 'index_flan' %}" class="btn btn-secondary my-2">Volver</a>
</div>

<div class="text-center my-4">
    
    <a href="{% url 'list_contact_web' %}" class="btn btn-secondary my-2">Lista de contactos</a>
</div>

<div class="d-flex justify-content-center">
    <form class="container border border-primary p-4" method="post" style="max-width: 600px;">
        {% csrf_token %}
        <div class="mb-3 text-center">
            <label class="form-label" for="customer_name">Nombre</label>
            <input class="form-control" type="text" name="customer_name" id="id_customer_name" required placeholder="Ingrese nombre">
        </div>
        <div class="mb-3 text-center">
            <label class="form-label" for="customer_email">Correo</label>
            <input class="form-control" type="email" name="customer_email" required id="id_customer_email"
                placeholder="Ingrese Correo electrónico">
        </div>
        <div class="mb-3 text-center">
            <label class="form-label" for="message">Mensaje</label>
            <input class="form-control" type="text" name="message" required id="id_message"
                placeholder="Ingrese mensaje">
        </div>
        
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>
</div>
{% endblock %}

desafio5/templates/web/contact_success.html
{% extends '../layouts/base.html' %}


{% block title %}
OnlyFlans | Contacto
{% endblock %}


{% block content %}
<div class="alert alert-success" role="alert">
    Gracias por contactarnos! Nos pondremos en contacto contigo lo más pronto posible.
</div>
<!-- enlace -->

    {% endblock %}

desafio5/templates/web/index.html
{% extends '../layouts/base.html' %}
{% block title %}
OnlyFlans|index
{% endblock %}

{% block content %}
<h1 class="text-center">Pagina index</h1>
<div class="container-fluid">
    <div class="row">
        {% for flan in flans %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img src="{{ flan.image_url }}" class="card-img-top" alt="{{ flan.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ flan.short_name }}</h5>
                    <p class="card-text">{{ flan.description }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

desafio5/templates/web/list_contact.html
{% extends '../layouts/base.html' %}


{% block title %}
OnlyFlans | Lista Contacto
{% endblock %}


{% block content %}
<h1 class="text-center">Listas</h1>
<div class="container-fluid">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Correo</th>
                <th scope="col">Mensaje</th>
            </tr>
        </thead>
        <tbody>
            {% for contact in contacts %}
            <tr>
                <td>{{ contact.id }}</td>
                <td>{{ contact.customer_name }}</td>
                <td>{{ contact.customer_email}}</td>
                <td>{{ contact.message}}</td>
            </tr>
            {% endfor %}


        </tbody>
    </table>

</div>
{% endblock %}

desafio5/templates/web/welcome.html
{% extends '../layouts/base.html' %}
{% block title %}
OnlyFlans|Bienvenido
{% endblock %}

{% block content %}
<h1 class="text-center">Pagina Bienvenido</h1>
<div class="container-fluid">
    <div class="row">
        {% for flan in flans %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img src="{{ flan.image_url }}" class="card-img-top" alt="{{ flan.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ flan.short_name }}</h5>
                    <p class="card-text">{{ flan.description }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}